.github/CODEOWNERS
_Adiciona reviews para as prs._
Adicionará automaticamente os usuários como reviews de uma pr
=> chore: adiciona usuários para reviews das pr

.editorconfig
=> chore: adiciona editorconfig

.vscode/extensions.json
_Adiciona configuração ao extensions._
Inclusão de alguma extensões que seria importante todos terem
=> chore: adiciona configuração ao extensions

styles/theme.ts
=> feat: adiciona cores do thema

src/components/Menu/index.stories.ts
_Forneça uma visão geral do(a) issue, feature, etc._
_Adicione contexto para as alterações realizadas. Imagens e vídeos ajudam a exemplificar._
=> fix: build

src/components/Input/index.stories.ts, src/components/Input/index.tsx, src/components/Input/styles.ts, styles/theme.ts
=> feat: adiciona componente Input

src/app/home/page.tsx, src/templates/BaseHome/index.tsx, src/templates/BaseHome/styles.ts
criando base inicial para home 
_Adicione contexto para as alterações realizadas. Imagens e vídeos ajudam a exemplificar._
=> feat: base home

src/components/Input/index.stories.ts, src/components/Input/index.tsx, src/components/Input/styles.ts
=> refactor: reestrutura input

src/components/Checkbox/index.stories.ts, src/components/Checkbox/index.tsx, src/components/Checkbox/styles.ts, src/components/Input/index.tsx
_Adiciona componente Checkbox._
- Adiciona callback no input
- Adiciona componenten Checkbox
=> feat: adiciona componente Checkbox

src/components/Button/index.tsx, src/components/Create/styles.ts, src/components/FullModal/index.tsx, src/components/FullModal/styles.ts, src/components/Input/index.stories.ts, src/components/Input/index.tsx, src/components/Link/index.stories.ts, src/components/Link/index.tsx, src/components/Link/styles.ts, src/components/Login/index.stories.ts, src/components/Login/index.tsx, src/components/Login/styles.ts, src/components/Modal/styles.ts, src/templates/BaseHome/index.tsx
_Cria layout formulario de login._
- Cria componente de link
- Incrementa componente de Input com type password
- Ajusta modal
=> feat: cria layout formulario de login

db.json, yarn.lock
Alterando db.json
_Forneça uma visão geral do(a) issue, feature, etc._
_Adicione contexto para as alterações realizadas. Imagens e vídeos ajudam a exemplificar._
=> refactor: alterando db.json

src/app/api/users/route.ts, src/app/home/page.tsx, src/services/useLogin.ts
_Adiciona teste de chamada a api._
=> feat: adiciona teste de chamada a api

db.json
=> feat: update db.json

package-lock.json, package.json, src/app/api/users/route.ts, src/components/MyAcoount/index.tsx, yarn.lock
Adicionei logica de requisição para o get e put no users para o My Account
https://github.com/user-attachments/assets/3f77aa6c-78f4-4c7b-b255-3ec9c791ce38
=> feat: add functionality to fetch and update user information

package-lock.json, src/app/api/saldo/route.ts, src/app/page.tsx, src/components/BalanceCard/index.tsx, src/hooks/useAuth.ts, src/hooks/useSaldo.ts, yarn.lock
Integrando o component de saldo com a api
_Adicione contexto para as alterações realizadas. Imagens e vídeos ajudam a exemplificar._
=> feat: add saldo

src/app/page.tsx, src/app/styles.ts, yarn.lock
➡️ Layout responsivo 
➡️ Precisa add o login no layout do celular
=> feat(home): layout responsivo

src/app/page.tsx, src/app/styles.ts, src/components/HeaderHome/index.tsx, src/components/HeaderHome/styles.ts, src/config/menu.ts, src/templates/BaseHome/index.tsx, yarn.lock
_Reorganiza modal de login e criação de conta e adicionar botão na tela home._
=> feat: reorganiza modal de login e criaçao de conta

.gitignore, src/app/api/extrato/route.ts, src/components/Button/index.tsx, src/components/Button/styles.ts, src/components/Extrato/index.tsx, src/components/Extrato/styles.ts, src/components/Icons/index.tsx, src/components/Icons/svg/delete.tsx, src/components/Icons/svg/edit.tsx, src/components/SelectTypeTransaction/index.tsx
=> feat: add edit tipo do extrato

src/app/api/extrato/route.ts, src/components/Dialog/index.tsx, src/components/Extrato/index.tsx, src/components/Extrato/styles.ts, src/components/Input/index.tsx, src/components/Menu/index.stories.ts, src/config/menu.ts, styles/theme.ts
=> feat: add delete tipo do extrato

src/app/api/extrato/route.ts, src/app/api/saldo/route.ts, src/app/api/users/route.ts, src/app/posts/page.tsx, src/hooks/useSaldo.ts, src/services/auth.ts, yarn.lock
Neste PR atualizei a url local para a do https://json-server-vercel-tawny-one.vercel.app assim vai ajustar no deploy do vercel e funciona localmente também, agora que fizemos a base da estrutura dos nossos dados.
Como esta atualmente no link do vercel quebrando por que a URL esta local.
Como vai ficar usando a nova URL
N/A
=> refactor: update API URLto production server

src/app/api/extrato/route.ts, src/app/api/saldo/route.ts, src/app/api/users/route.ts, src/app/dashboard/page.tsx, src/app/posts/page.tsx, src/components/MyAcoount/index.tsx, src/components/TransactionCard/index.tsx, src/hooks/useSaldo.ts, src/services/auth.ts, yarn.lock
- Ajuste no ToastContainer para pegar as mensagens 
- Adição da URL do localhost
- Ajuste na logica do My Account
- Adição de loading no My Account
N/A
N/A
=> refactor: adjustments API_URL e ToastContainer

README.md, package-lock.json, package.json, yarn.lock
=> feat: criacao do readme

src/components/GraficAngularMFE/AngularRemoteApp.js, src/components/InvestmentsCard/index.tsx, src/components/InvestmentsCard/styles.ts
Finalizando as configurações para incluir o grafico do mfe
=> feat: incluindo grafico

src/components/BalanceCard/index.tsx, src/components/Extrato/components/Modal/index.tsx, src/components/Extrato/index.tsx, src/components/Extrato/types.ts, src/components/SelectTypeTransaction/index.tsx, src/components/TransactionCard/index.tsx, src/config/transactions.ts, src/hooks/useSaldo.ts, src/hooks/useTransaction.ts, src/pages/api/extrato/index.ts, src/redux/features/actions/extratos.ts, src/redux/features/actions/saldos.ts, src/redux/features/actions/transactions.ts, src/redux/features/slices/transactions.ts
_Refatora extrato e ajusta logica._
=> feat: refatora extrato e ajusta logica

src/components/TransactionCard/index.tsx, src/components/TransactionCard/styles.ts, src/hooks/useTransaction.ts, src/pages/dashboard/index.tsx, src/redux/features/actions/transactions.ts
adicao do campo upload no card de transacoes
=> feat: upload file to string base64 in transaction

src/components/Extrato/index.tsx, src/components/Extrato/styles.ts
Filtro de busca por mes e componente de pesquisa
https://github.com/user-attachments/assets/44d8e7a1-cf26-4f03-8057-76fc6ceb54d1
Desktop e Tablet estao funcionando, porem mobile esta dando erro na abertura do modal 
=> feat(extrato): adiciona filtro no extrato

package-lock.json, src/components/Extrato/index.tsx, src/components/TransactionCard/index.tsx, src/config/api.ts, src/hooks/useExtrato.ts, src/hooks/useTransaction.ts, src/redux/features/actions/extratos.ts, yarn.lock
Adicionei nova logica de paginação
https://github.com/user-attachments/assets/f0308e4c-bfc7-43ae-9320-b54366ece978
=> feat: add logic pagination

README.md
Alteraçao no readme para adicionar instruçoes do docker e informacoes sobre o redux, module federation e link do outro repositorio
=> feat: add docker instructions and redux info

Dockerfile, docker-compose.yml, package-lock.json
criacao dos arquivos do docker
=> feat: add dockerfile
